### PR TITLE
Adds localization (french)

### PR DESCRIPTION
**Pull request by frague59**
Hi, 

I've put :
+ update .gitignore : add pycharm `.idea/` directory
+ some localization stuff into the project : models / apps
+ Adds a `recursive-include` to locale folder (not tested)

### CODE REVIEW

**Comment by NaakkaDev** [comment]
Thanks! This is nice, but requires a few small tweaks:

### .gitignore
Remove the .mo file and include the .mo file, unless you know of a reason why it shouldn't be included? Django, wagtail and other plugins seems to have it in there. I'm still a bit new to the localization stuff. :)

### recursive-include:
Change the added line to below ones:
```
recursive-include wagtail_simple_gallery/locale *.po
recursive-include wagtail_simple_gallery/locale *.mo
```

### models.py
Move line 10 to line 5 and add empty line. I like to keep the imports nicely grouped.

I'll merge and put a new version to pypi after you have made these changes. 👍

**Comment by frague59** [comment]
Got it...

**Comment by frague59** [comment]
Pushed...

**Comment by NaakkaDev** [comment]
Thanks. Could you commit and push the .mo file too? Sorry if I wasn't clear enough earlier.

**Comment by frague59** [comment]
Done. Sorry and thanks :)

**Pull request merged**
